#!/usr/bin/env bash

set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

source "$(dirname $0)/constants"

# Only run for the first travis job
if [[ "${TRAVIS_JOB_NUMBER##*.}" == "1" ]]; then
  "$SCRIPT_DIR/publishJarIfMaster"
  # Upload coverage information to codecov.io (BETA)
  # Unsure about whether it will do coverage for all the code base as opposed to just core
  pip install --user codecov && codecov
fi
