#!/usr/bin/env bash

set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

#
# This script is intended to be run by continuous integration tools, allowing
# actual details of the build and test process to change without having to
# update CI configuration.
#

source "$(dirname $0)/constants"

echo "Script Path:   $SCRIPT_DIR"
echo "Root Path:     $WS_DIR"
echo "Temp Path:     $TEMP_DIR"
echo "Version:       $QUASAR_VERSION"
echo "Web Jar:       $QUASAR_WEB_JAR"
echo "Web Jar Dir:   $QUASAR_WEB_JAR_DIR"
echo "Web Jar Path:  $QUASAR_WEB_JAR_PATH"
echo "REPL Jar:      $QUASAR_REPL_JAR"
echo "REPL Jar Dir:  $QUASAR_REPL_JAR_DIR"
echo "REPL Jar Path: $QUASAR_REPL_JAR_PATH"

QUASAR_TEMP_JAR="$TEMP_DIR/$QUASAR_WEB_JAR"

QUASAR_MONGODB_TESTDB="quasar-test"
QUASAR_MONGODB_HOST_2_6="localhost:27018"
QUASAR_MONGODB_HOST_3_0="localhost:27019"

rm -rf "$TEMP_DIR"
mkdir -p "$TEMP_DIR"

# Build the pristine JAR without coverage:
# We cannot do this at the end is because it would require us to clean the project
# which would remove the coverage information that Jenkins expects to find in the workspace after the build
"$SBT" clean oneJar

# Save a copy of the "clean" oneJar, since running code coverage
# will produce a "dirty" version:
cp "$QUASAR_WEB_JAR_PATH" "$QUASAR_TEMP_JAR"

# Perform setup for integration tests:
if [[ ${LOCAL_MONGODB:-} == "true" ]] ; then
  export QUASAR_TEST_PATH_PREFIX="/${QUASAR_MONGODB_TESTDB}/"
  export QUASAR_MONGODB_2_6="{\"mongodb\": {\"connectionUri\": \"mongodb://${QUASAR_MONGODB_HOST_2_6}\"}}"
  export QUASAR_MONGODB_3_0="{\"mongodb\": {\"connectionUri\": \"mongodb://${QUASAR_MONGODB_HOST_3_0}\"}}"

  echo "Using local MongoDB config"
fi

# Build and run all tests everywhere (including integration)
# Note: scoverage is brain-dead, so each project's tests have to be run
# separately, and 'core' should be last, so that its report will include
# coverage in the core code provided by tests in other projects.
"$SBT" -DisCoverageRun=true -DisIsolatedEnv=${ISOLATED_ENV:=false} coverage 'project it' test 'project web' test 'project core' test

# Build completed, copy oneJar to right location:
mkdir -p $QUASAR_WEB_JAR_DIR
cp $QUASAR_TEMP_JAR $QUASAR_WEB_JAR_PATH

# Test to ensure the JAR file is valid:
"$SCRIPT_DIR/testJar"
TEST_STATUS=$?

echo "Result of Quasar JAR test: $TEST_STATUS"

exit $TEST_STATUS
