#!/usr/bin/env bash

set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

WS_DIR="$SCRIPT_DIR/.."

SBT="$WS_DIR/sbt"

TEMP_DIR="$WS_DIR/tmp"

mkdir -p "$TEMP_DIR"

# quasar version, from build.sbt:
QUASAR_VERSION=$(cat $WS_DIR/version.sbt | sed -n -e 's/^ *version.*:= "\(.*\)"[^\n]*/\1/p')

QUASAR_WEB_JAR="web_2.11-$QUASAR_VERSION-one-jar.jar"
QUASAR_WEB_JAR_DIR="$WS_DIR/web/target/scala-2.11"
QUASAR_WEB_JAR_PATH="$QUASAR_WEB_JAR_DIR/$QUASAR_WEB_JAR"

QUASAR_REPL_JAR="core_2.11-$QUASAR_VERSION-one-jar.jar"
QUASAR_REPL_JAR_DIR="$WS_DIR/core/target/scala-2.11"
QUASAR_REPL_JAR_PATH="$QUASAR_REPL_JAR_DIR/$QUASAR_REPL_JAR"

echo "Quasar Version: $QUASAR_VERSION"
