#!/bin/bash

set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

WS_DIR="$SCRIPT_DIR/.."

SBT="$WS_DIR/sbt"

TEMP_DIR="$WS_DIR/tmp"

mkdir -p "$TEMP_DIR"

# slamengine version, from build.sbt:
SLAM_VERSION=$(cat $WS_DIR/build.sbt | sed -n -e 's/^ *version := "\(.*\)"[^\n]*/\1/p')

SLAM_WEB_JAR="web_2.11-$SLAM_VERSION-one-jar.jar"
SLAM_WEB_JAR_DIR="$WS_DIR/web/target/scala-2.11"
SLAM_WEB_JAR_PATH="$SLAM_WEB_JAR_DIR/$SLAM_WEB_JAR"

SLAM_REPL_JAR="core_2.11-$SLAM_VERSION-one-jar.jar"
SLAM_REPL_JAR_DIR="$WS_DIR/core/target/scala-2.11"
SLAM_REPL_JAR_PATH="$SLAM_REPL_JAR_DIR/$SLAM_REPL_JAR"