#! /bin/bash

dir=$(dirname $0)

if (( $# < 5 )); then
  echo 'usage: importTestData host port dbname user password'
  exit 1
fi  
  
MONGO_HOST="$1"
MONGO_PORT="$2"
MONGO_DB="$3"
MONGO_USER="$4"
MONGO_PASSWORD="$5"

importcmd="mongoimport -u $MONGO_USER -p $MONGO_PASSWORD --host $MONGO_HOST:$MONGO_PORT --db $MONGO_DB"

TEST_DIR="$dir/../it/src/test/resources/tests"

for f in $(find $TEST_DIR -name '*.data'); do
  coll=`expr "$f" : '.*/\(.*\)\.data'`
  echo "Loading $coll from $f..."
  $importcmd --collection $coll --file $f
done