#! /bin/bash
set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

# Download and run the correct version of mongodb, without using sudo, which
# is not available on Travis' new Docker-based platform.
# TODO: This won't be necessary when travis switches to 2.6 by default - see https://github.com/travis-ci/travis-ci/issues/2246

MONGO_VERSION=$1
MONGO_DIR=$2
MONGO_PORT=$3

CACHE_DIR=cache

mkdir -p $CACHE_DIR

if [ ! -f $CACHE_DIR/$MONGO_VERSION.tgz ]
then
  curl -s http://downloads.mongodb.org/linux/$MONGO_VERSION.tgz > $CACHE_DIR/$MONGO_VERSION.tgz
fi

tar -zxf $CACHE_DIR/$MONGO_VERSION.tgz
mv $MONGO_VERSION $MONGO_DIR

mkdir -p $MONGO_DIR-data
$MONGO_DIR/bin/mongod --dbpath $MONGO_DIR-data --port $MONGO_PORT > /dev/null &

sleep 5s
