#! /bin/bash
set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

# Download and run the correct version of mongodb, without using sudo, which
# is not available on Travis' new Docker-based platform.
# TODO: This won't be necessary when travis switches to 2.6 by default - see https://github.com/travis-ci/travis-ci/issues/2246

MONGO_VERSION=mongodb-linux-x86_64-2.6.6
CACHE_DIR=cache

mkdir -p $CACHE_DIR

if [ ! -f $CACHE_DIR/$MONGO_VERSION.tgz ]
then
  curl http://downloads.mongodb.org/linux/$MONGO_VERSION.tgz > $CACHE_DIR/$MONGO_VERSION.tgz
fi

tar -zxvf $CACHE_DIR/$MONGO_VERSION.tgz
mv $MONGO_VERSION mongo

mkdir -p mongodata
mongo/bin/mongod --dbpath mongodata &

sleep 5s
