#!/bin/bash

#
# This script is intended to be run by continuous integration tools, allowing 
# actual details of the build and test process to change without having to 
# update CI configuration.
#

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

SBT="$DIR/../sbt"

# Build and run all tests everywhere (including integration)
"$SBT" -DisCoverageRun=true coverage test oneJar

# Code coverage
if [ "$TRAVIS_BUILD" = "true" ] ; then
  "$SBT" coverageAggregate coveralls
else
  "$SBT" coverageAggregate
fi

# Build completed
# "$SBT" clean 'project web' oneJar