#!/bin/bash

#
# This script is intended to be run by continuous integration tools, allowing 
# actual details of the build and test process to change without having to 
# update CI configuration.
#

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

"$DIR/../sbt" -DisCoverageRun=true clean 'project web' oneJar 'project /' coverage 'project core' test 'project it' test 
