#!/bin/bash

set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

# Create a tag/release on github, and upload the already-built JAR.
# Using curl to POST to the github API.

source "$(dirname $0)/constants"

BUILD_NUMBER=$1
if [[ -z "$BUILD_NUMBER" ]]; then
    echo "usage: $0 BUILD_NUMBER"
    exit 1
fi

if [[ -z "$GITHUB_TOKEN" ]]; then
    echo "GITHUB_TOKEN not defined"
    exit 1
fi

# owner/repo and commit for the current dir:
REPO=$(git ls-remote --get-url origin | sed -n -e 's_git@github.com:\(.*\).git_\1_p' -e 's_https://github.com/\(.*\).git_\1_p')
COMMIT=$(git rev-parse HEAD)

if [[ ! -s "$SLAM_WEB_JAR_PATH" ]]; then
    echo "jar not found: $SLAM_WEB_JAR_PATH"
    exit 1
fi


TAG_NAME="v$VERSION-$BUILD_NUMBER"
PRERELEASE='true'
NAME="SlamEngine $VERSION, Build #$BUILD_NUMBER"
BODY=""  # Defaults to the latest commit comment

echo "Creating release/tag $TAG_NAME from $COMMIT"

RELEASE_ID=$(curl -s \
    -H "Authorization: token $GITHUB_TOKEN" \
    https://api.github.com/repos/$REPO/releases \
    -d "{ \"tag_name\": \"$TAG_NAME\", \"target_commitish\": \"$COMMIT\", \"name\": \"$NAME\", \"body\": \"$BODY\", \"prerelease\": $PRERELEASE }" | \
  sed -n -e 's/"id": \(.*\),/\1/p' | \
  tr -d ' ' | \
  head -n 1)

if [[ -z "$RELEASE_ID" ]]; then
    echo "Release not created"
    exit 1
fi
echo "Created release: \"$RELEASE_ID\""

echo "Uploading $SLAM_WEB_JAR..."
curl -s \
  -H "Authorization: token $GITHUB_TOKEN" \
  -H "Content-Type: application/zip" \
  https://uploads.github.com/repos/$REPO/releases/$RELEASE_ID/assets?name=$SLAM_WEB_JAR \
  --data-binary "@$SLAM_WEB_JAR_PATH" \
  > /dev/null
echo "  done"

echo "See https://github.com/$REPO/releases/tag/$TAG_NAME"

