#!/usr/bin/env bash

set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

# Create a tag/release on github, and upload the already-built JAR.
# Using curl to POST to the github API.

source "$(dirname $0)/constants"

if [[ ! -v GITHUB_TOKEN ]] ; then
    echo "GITHUB_TOKEN not defined, skipping publishing JAR"

    exit 0
fi

# only publish on slamdata/quasar#master
if [[ "$TRAVIS" == "true" && "$TRAVIS_BRANCH" == "master" && "$TRAVIS_REPO_SLUG" == "slamdata/quasar" ]] ; then
  "$SBT" 'project web'    githubRelease
else
  echo "GITHUB_TOKEN defined, but Travis not running in slamdata/quasar#master, so skipping publish"
fi
