#!/bin/bash

set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

# Takes one argument, the name of the wip branch (without "wip/").
# This starts a new wip branch, publishes it and tracks that

branch=${1:-}
if [[ -z "$branch" ]]; then
    echo "usage: $0 BRANCH"
    exit 1
fi

upstream="upstream/master"
wip="wip/$branch"

git fetch --all
git checkout -b $wip $upstream
git push --set-upstream origin $wip:$wip
